config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
    match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :tests

  root 'homes#index'

  get 'homes/aboutus', :path=>"aboutus"
  get 'homes/contactus', :path=>"contactus"

  resources :galleries
  resources :images

end

app/views/partial/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted">This Bootstrap Example courtesy <a href="http://www.bootply.com">Bootply.com</a></p>
  </div>
</div>

app/views/partial/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-custom navbar-inverse navbar-static-top" id="nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav nav-justified">
          <li><%= link_to 'Home', root_path %></li>
          <li><a href="#section3">News</a></li>
         <li><%= link_to 'About', homes_aboutus_path %>  </li>
          <li><%= link_to 'Contact', homes_contactus_path %> </li>
          <% if user_signed_in? %>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else %>
            <li><%= link_to "Join as Member", new_user_registration_path, :class => 'navbar-link'  %> </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login <b class="caret"></b></a>
              <ul class="dropdown-menu">
               <li><div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div></li>
                <li><%= link_to "Facebook", "/users/auth/facebook", id: "sign_in" %></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Google</a></li>
                
                <li><%= link_to "Custom Login", new_user_session_path, :class => 'navbar-link'  %> </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container -->
</div><!--/.navbar -->


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '761141683964471',
      xfbml      : true,
      version    : 'v2.1'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/partial/_masthead_header.html.erb
<header class="masthead bk-images">
    <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1><a href="#" title="Bootstrap Template">Happy Scroll</a>
          <p class="lead">{A Bootstrap Template}</p></h1>
      </div>
      <div class="col-sm-6">
        <div class="pull-right  hidden-xs">    
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><h3><i class="glyphicon glyphicon-cog"></i></h3></a>
          <ul class="dropdown-menu">
              <li><a href="#"><i class="glyphicon glyphicon-chevron-right"></i> Link</a></li>
              <li><a href="#"><i class="glyphicon glyphicon-user"></i> Link</a></li>
              <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Link</a></li>
              <li><a href="#"><i class="glyphicon glyphicon-cog"></i> Link</a></li>
          </ul>
        </div>
      </div>
    </div>
    </div>
</header>

<style type="text/css">
  .bk-images{
    background-image:url(/assets/images/images.jpeg); 
  }
</style>