config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
    match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :tests

  root 'homes#index'

  get 'homes/aboutus', :path=>"aboutus"
  get 'homes/contactus', :path=>"contactus"

  resources :galleries
  resources :images

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  #has_many :images
  has_many :images, as: :imageable
  belongs_to :user
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @gallery = Gallery.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @gallery = Gallery.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
  	@gallery = Gallery.new(gallery_params)
    @gallery.user_id = current_user.id
    

    respond_to do |format|
      if @gallery.save
      	@gallery.images.build({:avatar =>params[:gallery][:avatar], :imageable_id=> @gallery.id,:imageable_type=>params[:controller]})
        format.html { redirect_to @gallery, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name,:des)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, :html => {:multipart => true} do |f| %>
  <%#= f.error_messages %>
   <%#= f.hidden_field :user_id %>
 
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :des %><br />
    <%= f.text_field :des %>
  </p>
  <p>
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </p>
  
  <p><%= f.submit %></p>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing test</h1>

<%= render 'form' %>

<%= link_to 'Show', @test %> |
<%= link_to 'Back', tests_path %>

app/views/galleries/index.html.erb
<h1>Listing tests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tests.each do |test| %>
      <tr>
        <td><%= test.name %></td>
        <td><%= link_to 'Show', test %></td>
        <td><%= link_to 'Edit', edit_test_path(test) %></td>
        <td><%= link_to 'Destroy', test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test', new_test_path %>

app/views/galleries/new.html.erb
<h1>New test</h1>

<%= render 'form' %>

<%= link_to 'Back', tests_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
  <strong>DES:</strong>
  <%= @gallery.des %>
  
  <% @gallery.images.each do |img| %>
      <tr>
        <%= image_tag img.avatar_url.to_s %>
      </tr>
    <% end %>
</p>